version: "3"

services:
  api:
    build: ./backend
    ports: 
      - 5000:5000
    environment:
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - API_BASE=${API_BASE}
    volumes:
      - ./backend:/app

