version: "3"

services:
  api:
    build: ./backend
    ports: 
      - 5000:5000
    environment:
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - API_BASE=${API_BASE}
      - AI_HOST=${AI_HOST}
      - AI_PORT=${AI_PORT}
    volumes:
      - ./backend:/app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: tibame-ai233-01-locostall
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  admin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80

volumes:
  db-data:

