version: "3"

services:
  # web:
  #   # 資料夾路徑
  #   build: ./frontend
  #   ports:
  #     # host : container
  #     - 5173:3000
  #   volumes:
  #     - "./frontend:/project"
  #     - "/node_modules"

  api:
    build: ./backend
      # host : container
    ports: 
      - 5000:5000
    environment: 
        PORT: 5000
        FLASK_DEBUG: 1
    # secrets:
    #   - my_secret

  # app:
  #   build: ./app

  db:
    image: mysql
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3307"
    volumes:
      - db-data:/var/lib/mysql

  admin:
    image: phpmyadmin
    # restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80

# secrets:
#   my_secret:
#     file: ./backend/.env

volumes:
  db-data: